name: Deploy to EC2

on:
  push:
    branches:
      - main  # You can change this to the branch you want to deploy from

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up SSH Key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            cd /var/www/myapp || exit 1
            git pull origin main || exit 1  # Pull the latest changes
            source /var/www/myapp/myenv/bin/activate || exit 1  # Activate the virtual environment
            pip install -r requirements.txt || exit 1  # Install dependencies
            sudo systemctl restart gunicorn || exit 1  # Restart the Gunicorn server
            sudo systemctl restart nginx || exit 1  # Restart the Nginx server if necessary
          EOF
